[package]
name = "dlx-rs"
version = "0.0.0"
edition = "2021"
license = "CC0-1.0"
description = "Implementation of dancing links in rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
